export const CUSTOM_DATA_CREATE_REQUEST = "CUSTOM_DATA_CREATE_REQUEST";
export const CUSTOM_DATA_CREATE_SUCCESS = "CUSTOM_DATA_CREATE_SUCCESS";
export const CUSTOM_DATA_CREATE_FAIL = "CUSTOM_DATA_CREATE_FAIL";
export const CUSTOM_DATA_CREATE_RESET = "CUSTOM_DATA_CREATE_RESET";

export const CUSTOM_DATA_GET_REQUEST = "CUSTOM_DATA_GET_REQUEST";
export const CUSTOM_DATA_GET_SUCCESS = "CUSTOM_DATA_GET_SUCCESS";
export const CUSTOM_DATA_GET_FAIL = "CUSTOM_DATA_GET_FAIL";
export const CUSTOM_DATA_GET_RESET = "CUSTOM_DATA_GET_RESET";

export const CUSTOM_DATA_DELETE_REQUEST = "CUSTOM_DATA_DELETE_REQUEST";
export const CUSTOM_DATA_DELETE_SUCCESS = "CUSTOM_DATADELETET_SUCCESS";
export const CUSTOM_DATA_DELETE_FAIL = "CUSTOM_DATA_DELETE_FAIL";
export const CUSTOM_DATA_DELETE_RESET = "CUSTOM_DATA_DELETE_RESET";

export const CUSTOM_SINGLE_DATA_GET_REQUEST = "CUSTOM_SINGLE_DATA_GET_REQUEST";
export const CUSTOM_SINGLE_DATA_GET_SUCCESS = "CUSTOM_SINGLE_DATA_GET_SUCCESS";
export const CUSTOM_SINGLE_DATA_GET_FAIL = "CUSTOM_SINGLE_DATA_GET_FAIL";
export const CUSTOM_SINGLE_DATA_GET_RESET = "CUSTOM_SINGLE_DATA_GET_RESET";

export const CUSTOM_SINGLE_DATA_UPDATE_REQUEST =
  "CUSTOM_SINGLE_DATA_UPDATE_REQUEST";
export const CUSTOM_SINGLE_DATA_UPDATE_SUCCESS =
  "CUSTOM_SINGLE_DATA_UPDATE_SUCCESS";
export const CUSTOM_SINGLE_DATA_UPDATE_FAIL = "CUSTOM_SINGLE_DATA_UPDATE_FAIL";
export const CUSTOM_SINGLE_DATA_UPDATE_RESET =
  "CUSTOM_SINGLE_DATA_UPDATE_RESET";
