export const CUSTOM_DATA_CREATE_REQUEST = "CUSTOM_DATA_CREATE_REQUEST";
export const CUSTOM_DATA_CREATE_SUCCESS = "CUSTOM_DATA_CREATE_SUCCESS";
export const CUSTOM_DATA_CREATE_FAIL = "CUSTOM_DATA_CREATE_FAIL";
export const CUSTOM_DATA_CREATE_RESET = "CUSTOM_DATA_CREATE_RESET";

export const CUSTOM_DATA_GET_REQUEST = "CUSTOM_DATA_GET_REQUEST";
export const CUSTOM_DATA_GET_SUCCESS = "CUSTOM_DATA_GET_SUCCESS";
export const CUSTOM_DATA_GET_FAIL = "CUSTOM_DATA_GET_FAIL";
export const CUSTOM_DATA_GET_RESET = "CUSTOM_DATA_GET_RESET";
