export const USER_GET_REQUEST = "USER_GET_REQUEST";
export const USER_GET_SUCCESS = "USER_GET_SUCCESS";
export const USER_GET_FAIL = "USER_GET_FAIL";
export const USER_GET_RESET = "USER_GET_RESET";

export const SINGLE_USER_GET_REQUEST = "SINGLE_USER_GET_REQUEST";
export const SINGLE_USER_GET_SUCCESS = "SINGLE_USER_GET_SUCCESS";
export const SINGLE_USER_GET_FAIL = "SINGLE_USER_GET_FAIL";
export const SINGLE_USER_GET_RESET = "SINGLE_USER_GET_RESET";

export const USER_CREATE_REQUEST = "USER_CREATE_REQUEST";
export const USER_CREATE_SUCCESS = "USER_CREATE_SUCCESS";
export const USER_CREATE_FAIL = "USER_CREATE_FAIL";
export const USER_CREATE_RESET = "USER_CREATE_RESET";

export const SINGLE_USER_UPDATE_REQUEST = "SINGLE_USER_UPDATE_REQUEST";
export const SINGLE_USER_UPDATE_SUCCESS = "SINGLE_USER_UPDATE_SUCCESS";
export const SINGLE_USER_UPDATE_FAIL = "SINGLE_USER_UPDATE_FAIL";
export const SINGLE_USER_UPDATE_RESET = "SINGLE_USER_UPDATE_RESET";

export const USER_DELETE_REQUEST = "USER_DELETE_REQUEST";
export const USER_DELETE_SUCCESS = "USER_DELETE_SUCCESS";
export const USER_DELETE_FAIL = "USER_DELETE_FAIL";
export const USER_DELETE_RESET = "USER_DELETE_RESET";
