export const DATABASE_CREATE_REQUEST = "DATABASE_CREATE_REQUEST";
export const DATABASE_CREATE_SUCCESS = "DATABASE_CREATE_SUCCESS";
export const DATABASE_CREATE_FAIL = "DATABASE_CREATE_FAIL";
export const DATABASE_CREATE_RESET = "DATABASE_CREATE_RESET";
