export const EMPLOYEE_ID = "EMPLOYEE_ID";
export const EMPLOYEE_ID_RESET = "EMPLOYEE_ID";

export const EMPLOYEE_CREATE_REQUEST = "EMPLOYEE_CREATE_REQUEST";
export const EMPLOYEE_CREATE_SUCCESS = "EMPLOYEE_CREATE_SUCCESS";
export const EMPLOYEE_CREATE_FAIL = "EMPLOYEE_CREATE_FAIL";
export const EMPLOYEE_CREATE_RESET = "EMPLOYEE_CREATE_RESET";

export const EMPLOYEES_GET_REQUEST = "EMPLOYEES_GET_REQUEST";
export const EMPLOYEES_GET_SUCCESS = "EMPLOYEES_GET_SUCCESS";
export const EMPLOYEES_GET_FAIL = "EMPLOYEES_GET_FAIL";
export const EMPLOYEES_GET_RESET = "EMPLOYEES_GET_RESET";

export const EMPLOYEE_DELETE_REQUEST = "EMPLOYEE_DELETE_REQUEST";
export const EMPLOYEE_DELETE_SUCCESS = "EMPLOYEE_DELETE_SUCCESS";
export const EMPLOYEE_DELETE_FAIL = "EMPLOYEE_DELETE_FAIL";
export const EMPLOYEE_DELETE_RESET = "EMPLOYEE_DELETE_RESET";

export const EMPLOYEE_GET_REQUEST = "EMPLOYEE_GET_REQUEST";
export const EMPLOYEE_GET_SUCCESS = "EMPLOYEE_GET_SUCCESS";
export const EMPLOYEE_GET_FAIL = "EMPLOYEE_GET_FAIL";
export const EMPLOYEE_GET_RESET = "EMPLOYEE_GET_RESET";

export const EMPLOYEE_UPDATE_REQUEST = "EMPLOYEE_UPDATE_REQUEST";
export const EMPLOYEE_UPDATE_SUCCESS = "EMPLOYEE_UPDATE_SUCCESS";
export const EMPLOYEE_UPDATE_FAIL = "EMPLOYEE_UPDATE_FAIL";
export const EMPLOYEE_UPDATE_RESET = "EMPLOYEE_UPDATE_RESET";
